spring:
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
    #初始化表结构
    jdbc:
#      initialize-schema: never
       initialize-schema: always #第一次使用always 切记
  datasource:
    db:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://www.jsan.pro:3306/rhino?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&failOverReadOnly=false&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true&allowMultiQueries=true
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxIdle: 100
      maxActive: 200
      maxWait: 5000
      testOnBorrow: false
      validationQuery: SELECT 1
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 1800000
      numTestsPerEvictionRun: 100
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB


  redis:
    host: www.jsan.pro
    password: 123.com

rhino:
  admin:
    userid: 1
page:
  pagesize: 10

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-column-underline: true
    id-type: 1
    capital-mode: true
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql
